### ISSUE TITLE
SNPE run with DSP on Windows 11 Arm 

### ISSUE THREAD

**Issue by LiangJy123** [quic/sample-apps-for-Qualcomm-Robotics-RB5-platform#58]
Hi ,
As the title , I want to  run AI demo with DSP on windows.
I try the sample app which is contained in  the SDK folder. It's failed.
Does the sdk support running with DSP? 
And any suggestions to troubleshot the problem?( library , drivers... ) 

Devices:
Surface Pro X ( Qualcomm(R) Hexagon(TM) 690 dsp )

Sdk:
snapdragon_npe_sdk.win.1.0_installer_15500.1

Sample:
snpe-net-run.exe

Log:
![dsp](https://user-images.githubusercontent.com/13048899/144166470-f0920b58-79e9-43d0-b778-bb8d24c62bc2.png)

**Comment by LiangJy123** [comment]
I find the way . 
Open powershell as admin .
![DSP_success_](https://user-images.githubusercontent.com/13048899/144398659-6a54b256-484e-4a30-b5e1-138d50a9b6f1.png)

**Comment by flyfish30** [comment]
Hi, how to get the snpe sdk snapdragon_npe_sdk.win.1.0_installer_15500.1? Is there a new version snpe available?
