### ISSUE TITLE
Not able to read stream from the USB Camera module.

### ISSUE THREAD

**Issue by veeramallirajesh** [quic/sample-apps-for-Qualcomm-Robotics-RB5-platform#7]
Hello,

I am trying to access the video stream from the USB camera and when I run ./usbcam_display /dev/video0 it complains as below:

** (usbcam_display:2680): WARNING **: 15:29:47.963: Could not bind to gbm_buffer_backend
Start
Error: Could not open device '/dev/video0' for reading and writing.
Stop

List of devices I see are:
sh-4.4# v4l2-ctl --list-devices
msm_vidc_vdec ():
	/dev/video32
	/dev/video33
	/dev/radio0
	/dev/v4l-subdev2
	/dev/v4l-subdev3
	/dev/v4l-subdev4
	/dev/v4l-subdev5
	/dev/v4l-subdev6
	/dev/v4l-subdev7
	/dev/v4l-subdev8
	/dev/v4l-subdev9

Failed to open /dev/video0: Operation already in progress
Do you know what is the issue here?

**Comment by wanghaow** [comment]
Hello

According to v4l2-ctl output, there are only two possible device files of camera video output: video32 and video33. ‘/dev/video0’ does not work because it is not a v4l2 device in the system.

Please try to display /dev/video32 or /dev/video33 in this case.

 ./usbcam_display /dev/video32
 ./usbcam_display /dev/video33

**Comment by veeramallirajesh** [comment]
Hello,

I already tried to access the camera using video32 and video33 as in the commands you mentioned above but it did not work.
I have changed the camera and the error is as below:
```
```
sh-4.4# v4l2-ctl --list-devices
msm_vidc_vdec ():
	/dev/video32
	/dev/video33
	/dev/radio0
	/dev/v4l-subdev2
	/dev/v4l-subdev3
	/dev/v4l-subdev4
	/dev/v4l-subdev5
	/dev/v4l-subdev6
	/dev/v4l-subdev7
	/dev/v4l-subdev8
	/dev/v4l-subdev9

3.0 USB Camera: 3.0 USB Camera (usb-xhci-hcd.0.auto-1.2):
	/dev/video0
	/dev/video1

sh-4.4# ./usbcam_display /dev/video0

** (usbcam_display:2400): WARNING **: 11:05:14.860: Could not bind to gbm_buffer_backend
Start
Error: Internal data stream error.
Stop
sh-4.4# ./usbcam_display /dev/video1

** (usbcam_display:2403): WARNING **: 11:05:18.721: Could not bind to gbm_buffer_backend
Start
Error: Device '/dev/video1' is not a capture device.
Stop
sh-4.4# ./usbcam_display /dev/video32

** (usbcam_display:2406): WARNING **: 11:05:21.321: Could not bind to gbm_buffer_backend
Start

(usbcam_display:2406): GStreamer-CRITICAL **: 11:05:21.324: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2406): GStreamer-CRITICAL **: 11:05:21.324: gst_value_set_int_range_step: assertion 'start < end' failed
Error: Internal data stream error.
Stop
sh-4.4# ./usbcam_display /dev/video33

** (usbcam_display:2409): WARNING **: 11:05:24.211: Could not bind to gbm_buffer_backend
Start

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.214: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.214: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.215: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.215: gst_value_set_int_range_step: assertion 'start < end' failed
Error: Internal data stream error.
Stop
```

could you help me in solving this? Thank you.

**Comment by veeramallirajesh** [comment]
> Hello,
> 
> I already tried to access the camera using video32 and video33 as in the commands you mentioned above but it did not work.
> I have changed the camera and the error is as below:
> 
> ```
> sh-4.4# v4l2-ctl --list-devices
> msm_vidc_vdec ():
> 	/dev/video32
> 	/dev/video33
> 	/dev/radio0
> 	/dev/v4l-subdev2
> 	/dev/v4l-subdev3
> 	/dev/v4l-subdev4
> 	/dev/v4l-subdev5
> 	/dev/v4l-subdev6
> 	/dev/v4l-subdev7
> 	/dev/v4l-subdev8
> 	/dev/v4l-subdev9
> 
> 3.0 USB Camera: 3.0 USB Camera (usb-xhci-hcd.0.auto-1.2):
> 	/dev/video0
> 	/dev/video1
> 
> sh-4.4# ./usbcam_display /dev/video0
> 
> ** (usbcam_display:2400): WARNING **: 11:05:14.860: Could not bind to gbm_buffer_backend
> Start
> Error: Internal data stream error.
> Stop
> sh-4.4# ./usbcam_display /dev/video1
> 
> ** (usbcam_display:2403): WARNING **: 11:05:18.721: Could not bind to gbm_buffer_backend
> Start
> Error: Device '/dev/video1' is not a capture device.
> Stop
> sh-4.4# ./usbcam_display /dev/video32
> 
> ** (usbcam_display:2406): WARNING **: 11:05:21.321: Could not bind to gbm_buffer_backend
> Start
> 
> (usbcam_display:2406): GStreamer-CRITICAL **: 11:05:21.324: gst_value_set_int_range_step: assertion 'start < end' failed
> 
> (usbcam_display:2406): GStreamer-CRITICAL **: 11:05:21.324: gst_value_set_int_range_step: assertion 'start < end' failed
> Error: Internal data stream error.
> Stop
> sh-4.4# ./usbcam_display /dev/video33
> 
> ** (usbcam_display:2409): WARNING **: 11:05:24.211: Could not bind to gbm_buffer_backend
> Start
> 
> (usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.214: gst_value_set_int_range_step: assertion 'start < end' failed
> 
> (usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.214: gst_value_set_int_range_step: assertion 'start < end' failed
> 
> (usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.215: gst_value_set_int_range_step: assertion 'start < end' failed
> 
> (usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.215: gst_value_set_int_range_step: assertion 'start < end' failed
> Error: Internal data stream error.
> Stop
> could you help me in solving this? Thank you.
> ```

**Comment by veeramallirajesh** [comment]
Hello,

I already tried to access the camera using video32 and video33 as in the commands you mentioned above but it did not work.
I have changed the camera module and the error is as below:
```
sh-4.4# v4l2-ctl --list-devices
msm_vidc_vdec ():
	/dev/video32
	/dev/video33
	/dev/radio0
	/dev/v4l-subdev2
	/dev/v4l-subdev3
	/dev/v4l-subdev4
	/dev/v4l-subdev5
	/dev/v4l-subdev6
	/dev/v4l-subdev7
	/dev/v4l-subdev8
	/dev/v4l-subdev9

3.0 USB Camera: 3.0 USB Camera (usb-xhci-hcd.0.auto-1.2):
	/dev/video0
	/dev/video1

sh-4.4# ./usbcam_display /dev/video0

** (usbcam_display:2400): WARNING **: 11:05:14.860: Could not bind to gbm_buffer_backend
Start
Error: Internal data stream error.
Stop
sh-4.4# ./usbcam_display /dev/video1

** (usbcam_display:2403): WARNING **: 11:05:18.721: Could not bind to gbm_buffer_backend
Start
Error: Device '/dev/video1' is not a capture device.
Stop
sh-4.4# ./usbcam_display /dev/video32

** (usbcam_display:2406): WARNING **: 11:05:21.321: Could not bind to gbm_buffer_backend
Start

(usbcam_display:2406): GStreamer-CRITICAL **: 11:05:21.324: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2406): GStreamer-CRITICAL **: 11:05:21.324: gst_value_set_int_range_step: assertion 'start < end' failed
Error: Internal data stream error.
Stop
sh-4.4# ./usbcam_display /dev/video33

** (usbcam_display:2409): WARNING **: 11:05:24.211: Could not bind to gbm_buffer_backend
Start

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.214: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.214: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.215: gst_value_set_int_range_step: assertion 'start < end' failed

(usbcam_display:2409): GStreamer-CRITICAL **: 11:05:24.215: gst_value_set_int_range_step: assertion 'start < end' failed
Error: Internal data stream error.
Stop

could you help me in solving this? Thank you.

**Comment by wanghaow** [comment]
Hello

Please check the framerate and resolution to match that the camera can support. Although some cameras can not display all listed resolution and framerate, the information from v4l2-ctl is still valuable. 

It results in 'Internal data stream error' if the framerate and resolution not supported by the camera, 

In usbcam_display.c, line 76,77:

g_object_set(G_OBJECT(framefilter), "caps", 
             gst_caps_from_string("video/x-raw,framerate=15/1,width=1280,height=720"), NULL);

Change corresponding parameters to verify the result.

If this can not solve the problem, we will go further to figure it out.

============================================

In my case, I can list the support frame size and frame rate of the device:

root@qrb5165-rb5:/data/Gstreamer-Applications/gst_camera# v4l2-ctl --list-devices
msm_vidc_vdec ():
	/dev/video32
	/dev/video33
	/dev/radio0
	/dev/v4l-subdev2
	/dev/v4l-subdev3
	/dev/v4l-subdev4
	/dev/v4l-subdev5
	/dev/v4l-subdev6
	/dev/v4l-subdev7

Intel(R) RealSense(TM) Depth Ca (usb-xhci-hcd.0.auto-1.2):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
	/dev/video4
	/dev/video5

root@qrb5165-rb5:/data/Gstreamer-Applications/gst_camera# v4l2-ctl -d /dev/video4 --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2

	Index       : 1
	Type        : Video Capture
	Pixel Format: ''
	Name        : 36315752-1a66-a242-9065-d01814a

root@qrb5165-rb5:/data/Gstreamer-Applications/gst_camera# v4l2-ctl -d /dev/video4 --list-framesize=YUYV
ioctl: VIDIOC_ENUM_FRAMESIZES
	Size: Discrete 320x180
	Size: Discrete 320x240
	Size: Discrete 424x240
	Size: Discrete 640x360
	Size: Discrete 640x480
	Size: Discrete 848x480
	Size: Discrete 960x540
	Size: Discrete 1280x720
	Size: Discrete 1920x1080

root@qrb5165-rb5:/data/Gstreamer-Applications/gst_camera# v4l2-ctl -d /dev/video4 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2
		..........
		..........
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.167s (6.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.167s (6.000 fps)

	Index       : 1
	Type        : Video Capture
	Pixel Format: ''
	Name        : 36315752-1a66-a242-9065-d01814a
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)

============================================

Or you can use gst-launch to check the correctness of the pipleline.

In terminal on the board, start weston and use:
gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! videorate ! video/x-raw,framerate=15/1,width=1280,height=720 ! waylandsink width=1280 height=720 x=300 y=100

Change corresponding parameters to verify the output display.

Also you can connect the usb camera to a Ubuntu desktop to test the pipeline:

gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! videorate ! video/x-raw,framerate=15/1,width=1280,height=720 ! glimagesink

On Ubuntu, there is weston and wayland but you can use other display sinks for convenience.

Once you have workable framerate and resolution, you can put into usbcam_display.c to verify the result.

**Comment by veeramallirajesh** [comment]
Hello,

I am able to access a USB camera with "gst-launch" command with the below parameters:

gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! videorate ! video/x-raw,framerate=15/1,width=1280,height=720 ! waylandsink width=1280 height=720 x=300 y=100

When I update the same parameters in the usbcam_display.c file but I still get the same error as below:

root@qrb5165-rb5:/home/sample-apps-for-Qualcomm-Robotics-RB5-platform/Gstreamer-Applications/gst_camera# ./usbcam_display /dev/video0

** (usbcam_display:4391): WARNING **: 10:06:41.819: Could not bind to gbm_buffer_backend
Start
Error: Internal data stream error.
Stop

Lines in the usbcam_display.c: (I tried with width=1280/640 and height=640/480)
 g_object_set(G_OBJECT(framefilter), "caps",
 77                         gst_caps_from_string("video/x-raw,framerate=15/1,width=640,height=480"), NULL);
 78 
 79     g_object_set (G_OBJECT(sink), "x", 0, "y", 100, "width", 640, "height", 480, NULL);

Some more information:

root@qrb5165-rb5:/home/sample-apps-for-Qualcomm-Robotics-RB5-platform/Gstreamer-Applications/gst_camera# v4l2-ctl --list-devices
msm_vidc_vdec ():
	/dev/video32
	/dev/video33
	/dev/radio0
	/dev/v4l-subdev2
	/dev/v4l-subdev3
	/dev/v4l-subdev4
	/dev/v4l-subdev5
	/dev/v4l-subdev6
	/dev/v4l-subdev7
	/dev/v4l-subdev8
	/dev/v4l-subdev9

3.0 USB Camera: 3.0 USB Camera (usb-xhci-hcd.0.auto-1.2):
	/dev/video0
	/dev/video1

root@qrb5165-rb5:/home/sample-apps-for-Qualcomm-Robotics-RB5-platform/Gstreamer-Applications/gst_camera# v4l2-ctl -d /dev/video0 --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2

root@qrb5165-rb5:/home/sample-apps-for-Qualcomm-Robotics-RB5-platform/Gstreamer-Applications/gst_camera# v4l2-ctl -d /dev/video0 --list-framesize=YUYV
ioctl: VIDIOC_ENUM_FRAMESIZES
	Size: Discrete 1920x1080
	Size: Discrete 1280x720
	Size: Discrete 640x480
Thanks.

**Comment by wanghaow** [comment]
Hello

Since gst-launch works fine, the problem is the pipeline in the sample code.
Please do this patch manually to verify the result.

If it works, it may take time to merge this patch into the repository. 

===========================================================

diff --git a/Gstreamer-Applications/gst_camera/usbcam_display.c b/Gstreamer-Applications/gst_camera/usbcam_display.c
index e30f8e6..33f43fe 100644
--- a/Gstreamer-Applications/gst_camera/usbcam_display.c
+++ b/Gstreamer-Applications/gst_camera/usbcam_display.c
@@ -43,7 +43,7 @@ int main(int argc, char *argv[])
 {
     GMainLoop *loop;
 
-    GstElement *pipeline, *source, *videoconv, *framefilter, *sink;
+    GstElement *pipeline, *source, *videoconv, *videorate, *framefilter, *sink;
     GstBus *bus;
     guint bus_id;
 
@@ -59,6 +59,7 @@ int main(int argc, char *argv[])
     pipeline    = gst_pipeline_new("video-display");
     source      = gst_element_factory_make("v4l2src",      "v4l2-source");
     videoconv   = gst_element_factory_make("videoconvert", "video-convert");
+    videorate   = gst_element_factory_make("videorate",    "video-rate");
     framefilter = gst_element_factory_make("capsfilter",   "frame-filter");
     sink        = gst_element_factory_make("waylandsink",  "display");
 
@@ -66,7 +67,7 @@ int main(int argc, char *argv[])
     // we add videoconvert to convert the format from different usb camera input.
 
 
-    if (!pipeline || !source || !videoconv || !framefilter || !sink) {
+    if (!pipeline || !source || !videoconv || !videorate || !framefilter || !sink) {
         g_printerr ("Create element failed.\n");
         return -1;
     }
@@ -82,8 +83,8 @@ int main(int argc, char *argv[])
     bus_id = gst_bus_add_watch(bus, bus_callback, loop);
     gst_object_unref(bus);
 
-    gst_bin_add_many(GST_BIN(pipeline), source, videoconv, framefilter, sink, NULL);
-    gst_element_link_many(source, videoconv, framefilter, sink, NULL);
+    gst_bin_add_many(GST_BIN(pipeline), source, videoconv, videorate, framefilter, sink, NULL);
+    gst_element_link_many(source, videoconv, videorate, framefilter, sink, NULL);
 
     gst_element_set_state(pipeline, GST_STATE_PLAYING);
     g_print("Start\n");

**Comment by stanlin528** [comment]
The patch should be: (avoid the markdown format interference)

`diff --git a/Gstreamer-Applications/gst_camera/usbcam_display.c b/Gstreamer-Applications/gst_camera/usbcam_display.c
index e30f8e6..33f43fe 100644
--- a/Gstreamer-Applications/gst_camera/usbcam_display.c
+++ b/Gstreamer-Applications/gst_camera/usbcam_display.c
@@ -43,7 +43,7 @@ int main(int argc, char *argv[])
 {
     GMainLoop *loop;
 
-    GstElement *pipeline, *source, *videoconv, *framefilter, *sink;
+    GstElement *pipeline, *source, *videoconv, *videorate, *framefilter, *sink;
     GstBus *bus;
     guint bus_id;
 
@@ -59,6 +59,7 @@ int main(int argc, char *argv[])
     pipeline    = gst_pipeline_new("video-display");
     source      = gst_element_factory_make("v4l2src",      "v4l2-source");
     videoconv   = gst_element_factory_make("videoconvert", "video-convert");
+    videorate   = gst_element_factory_make("videorate",    "video-rate");
     framefilter = gst_element_factory_make("capsfilter",   "frame-filter");
     sink        = gst_element_factory_make("waylandsink",  "display");
 
@@ -66,7 +67,7 @@ int main(int argc, char *argv[])
     // we add videoconvert to convert the format from different usb camera input.
 
 
-    if (!pipeline || !source || !videoconv || !framefilter || !sink) {
+    if (!pipeline || !source || !videoconv || !videorate || !framefilter || !sink) {
         g_printerr ("Create element failed.\n");
         return -1;
     }
@@ -82,8 +83,8 @@ int main(int argc, char *argv[])
     bus_id = gst_bus_add_watch(bus, bus_callback, loop);
     gst_object_unref(bus);
 
-    gst_bin_add_many(GST_BIN(pipeline), source, videoconv, framefilter, sink, NULL);
-    gst_element_link_many(source, videoconv, framefilter, sink, NULL);
+    gst_bin_add_many(GST_BIN(pipeline), source, videoconv, videorate, framefilter, sink, NULL);
+    gst_element_link_many(source, videoconv, videorate, framefilter, sink, NULL);
 
     gst_element_set_state(pipeline, GST_STATE_PLAYING);
     g_print("Start\n");
`

**Comment by stanlin528** [comment]
The patch should be: (avoid markdown format interference)

```diff --git a/Gstreamer-Applications/gst_camera/usbcam_display.c b/Gstreamer-Applications/gst_camera/usbcam_display.c
index e30f8e6..33f43fe 100644
--- a/Gstreamer-Applications/gst_camera/usbcam_display.c
+++ b/Gstreamer-Applications/gst_camera/usbcam_display.c
@@ -43,7 +43,7 @@ int main(int argc, char *argv[])
 {
     GMainLoop *loop;
 
-    GstElement *pipeline, *source, *videoconv, *framefilter, *sink;
+    GstElement *pipeline, *source, *videoconv, *videorate, *framefilter, *sink;
     GstBus *bus;
     guint bus_id;
 
@@ -59,6 +59,7 @@ int main(int argc, char *argv[])
     pipeline    = gst_pipeline_new("video-display");
     source      = gst_element_factory_make("v4l2src",      "v4l2-source");
     videoconv   = gst_element_factory_make("videoconvert", "video-convert");
+    videorate   = gst_element_factory_make("videorate",    "video-rate");
     framefilter = gst_element_factory_make("capsfilter",   "frame-filter");
     sink        = gst_element_factory_make("waylandsink",  "display");
 
@@ -66,7 +67,7 @@ int main(int argc, char *argv[])
     // we add videoconvert to convert the format from different usb camera input.
 
 
-    if (!pipeline || !source || !videoconv || !framefilter || !sink) {
+    if (!pipeline || !source || !videoconv || !videorate || !framefilter || !sink) {
         g_printerr ("Create element failed.\n");
         return -1;
     }
@@ -82,8 +83,8 @@ int main(int argc, char *argv[])
     bus_id = gst_bus_add_watch(bus, bus_callback, loop);
     gst_object_unref(bus);
 
-    gst_bin_add_many(GST_BIN(pipeline), source, videoconv, framefilter, sink, NULL);
-    gst_element_link_many(source, videoconv, framefilter, sink, NULL);
+    gst_bin_add_many(GST_BIN(pipeline), source, videoconv, videorate, framefilter, sink, NULL);



+    gst_element_link_many(source, videoconv, videorate, framefilter, sink, NULL);
 
     gst_element_set_state(pipeline, GST_STATE_PLAYING);
     g_print("Start\n");
```

**Comment by veeramallirajesh** [comment]
Hey. Thank you so much for the patch and it works now.
